### ISSUE TITLE
启动CoreService时报错

### ISSUE THREAD

**Issue by JerryWoo** [quhailong/NetworkDisk_Storage#9]
如下报错，请问是什么原因呢：
2019-12-03 19:42:36.330  WARN 19988 --- [nfoReplicator-0] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failed with message: java.net.ConnectException: Connection refused: connect
2019-12-03 19:42:36.331  WARN 19988 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/SD01.digital.com - registration failed Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.9.13.jar:1.9.13]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.13.jar:1.9.13]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) ~[eureka-client-1.9.13.jar:1.9.13]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.9.13.jar:1.9.13]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.13.jar:1.9.13]
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:847) ~[eureka-client-1.9.13.jar:1.9.13]
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121) [eureka-client-1.9.13.jar:1.9.13]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Comment by quhailong** [comment]
> DiscoveryClient_UNKNOWN/SD01.digital.com - registration failed Cannot execute request on any known server

注册中心(pan-eureka-service)没有启动，或者是配置中心(pan-core-service)没有启动

**Comment by JerryWoo** [comment]
注册中心(pan-eureka-service)、配置中心(pan-config-service)都能正常启动，但是目前发现有四个服务启动不了，pan-core-service、pan-file-service、pan-share-service、pan-user-service，其他都能启动正常。这四个服务都是feign客户端，这四个貌似都找不到yml配置(实际上有)，读取了默认配置，启动了默认8080端口从而失败：
2019-12-04 15:39:05.051  INFO 32460 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:8888
2019-12-04 15:39:05.313  WARN 32460 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: Could not extract response: no suitable HttpMessageConverter found for response type [class org.springframework.cloud.config.environment.Environment] and content type [text/html;charset=UTF-8]
2019-12-04 15:39:05.321  INFO 32460 --- [           main] t.q.pan.core.CoreServiceApplication      : No active profile set, falling back to default profiles: default
2019-12-04 15:39:07.696  WARN 32460 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
2019-12-04 15:39:08.183  INFO 32460 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=f386ffa0-577d-3cb8-824f-ca94f30c3225
2019-12-04 15:39:08.721  INFO 32460 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-12-04 15:39:09.215  INFO 32460 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$27470fa3] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-12-04 15:39:11.998  INFO 32460 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)

**Comment by quhailong** [comment]
> 注册中心(pan-eureka-service)、配置中心(pan-config-service)都已正常启动【我把配置中心的端口号改为8888，eureka的端口号改为8761了】，但是目前发现有四个服务启动不了(pan-core-service、pan-file-service、pan-share-service、pan-user-service)，除了这个四个其他都能启动正常。这四个服务都是feign客户端，这四个貌似都找不到yml配置(实际上有)，读取了默认配置，启动了默认8080端口从而失败：
> 2019-12-04 15:39:05.051 INFO 32460 --- [ main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:8888
> 2019-12-04 15:39:05.313 WARN 32460 --- [ main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: Could not extract response: no suitable HttpMessageConverter found for response type [class org.springframework.cloud.config.environment.Environment] and content type [text/html;charset=UTF-8]
> 2019-12-04 15:39:05.321 INFO 32460 --- [ main] t.q.pan.core.CoreServiceApplication : **No active profile set, falling back to default profiles: default**
> 2019-12-04 15:39:07.696 WARN 32460 --- [ main] o.s.boot.actuate.endpoint.EndpointId : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
> 2019-12-04 15:39:08.183 INFO 32460 --- [ main] o.s.cloud.context.scope.GenericScope : BeanFactory id=f386ffa0-577d-3cb8-824f-ca94f30c3225
> 2019-12-04 15:39:08.721 INFO 32460 --- [ main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 2019-12-04 15:39:09.215 INFO 32460 --- [ main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$27470fa3] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 2019-12-04 15:39:11.998 INFO 32460 --- [ main] o.s.b.w.embedded.tomcat.TomcatWebServer : Tomcat initialized with port(s): **8080 (http)**

加微信说吧

**Comment by quhailong** [comment]
已更新readme说明
